services:
  app:
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG}
    container_name: ${CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    env_file:
      - ./config/.env.deploy
    ports:
      - "${PORT}:${PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app_network
   labels:
      - "deployment.environment=${APP_ENV}"
      - "deployment.date=${DEPLOYMENT_DATE}"
      - "deployment.sha=${DEPLOYMENT_SHA}"
      - "app.name=${APP_NAME}"
      - "app.version=${APP_VERSION}"

networks:
  app_network:
    name: ${APP_NAME}_${APP_ENV}_network
    driver: bridge
